version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poc
    ports:
      - 3308:3306
  
  admin:    
    image: adminer    
    ports:      
      - 8089:8080